from utils import run_bespokefit_all_smiles
import subprocess
import os

# List your config files here or use a wildcard/glob to find them
CONFIGS, = glob_wildcards("configs/{config}.yaml")

# Get hyperparameter tuning configs if they exist
if os.path.exists("hyperparameter_tuning/configs"):
    HP_CONFIGS, = glob_wildcards("hyperparameter_tuning/configs/{config}.yaml")
else:
    HP_CONFIGS = []

rule all:
    input:
        expand("results/{config}.benchmark.txt", config=CONFIGS)

rule get_hyperparameter_tuning_input:
    output:
        "hyperparameter_tuning/input/test_set/smiles.csv",
        "hyperparameter_tuning/input/test_set/test_set.json",
        "hyperparameter_tuning/input/validation_set/smiles.csv",
        "hyperparameter_tuning/input/validation_set/validation_set.json"
    shell:
        """
        mkdir -p hyperparameter_tuning/input
        cd hyperparameter_tuning/input
        curl https://zenodo.org/records/11385284/files/TNet500_minimal.zip?download=1 -o TNet500_minimal.zip
        unzip TNet500_minimal.zip
        rm TNet500_minimal.zip
        rm -r __MACOSX
        python ../scripts/create_dataset.py
        python ../scripts/split_valid_test.py
        cd ../..
        """

rule get_hyperparameter_tuning_configs:
    output:
        directory("hyperparameter_tuning/configs")
    shell:
        """
        mkdir -p hyperparameter_tuning/configs
        cd hyperparameter_tuning
        python scripts/create_configs.py
        cd ..
        """

rule run_hyperparameter_tuning:
    input:
        config_dir="hyperparameter_tuning/configs",
        smiles_file="hyperparameter_tuning/input/validation_set/smiles.csv"
    output:
        force_fields=expand("hyperparameter_tuning/output/{config}/combined_forcefield.offxml",
                                    config=HP_CONFIGS)
    run:
        for config in HP_CONFIGS:
            config_file = f"hyperparameter_tuning/configs/{config}.yaml"
            run_bespokefit_all_smiles(config_file,
                                      input.smiles_file,
                                      "hyperparameter_tuning",
                                      config, # Use the config name as subdir name
                                      from_precomputed=False)

# Analyse all the hyperparameter tuning results at once
rule analyse_hyperparameter_tuning:
    input:
        force_fields=expand("hyperparameter_tuning/output/{config}/combined_forcefield.offxml",
                                    config=HP_CONFIGS),
        input_data="hyperparameter_tuning/input/validation_set/validation_set.json"
    output:
        dummy_output="hyperparameter_tuning/analysis/dummy_output.txt"
    run:
        from yammbs.scripts.run_torsion_comparisons import main
        from pathlib import Path
        analysis_dir = Path("hyperparameter_tuning/analysis")
        analysis_dir.mkdir(parents=True, exist_ok=True)
        os.chdir(analysis_dir)

        extra_force_fields = [
            f"../output/{config}/combined_forcefield.offxml"
            for config in HP_CONFIGS
        ]

        cmd = [
            "yammbs_analyse_torsions",
            "--base-force-fields", "openff_unconstrained-2.3.0-rc2.offxml",
            "--qcarchive-torsion-data", "../input/validation_set/validation_set.json",
        ]
        # for ff in extra_force_fields:
        #     cmd.extend(["--extra-force-fields", ff])

        subprocess.run(cmd, check=True)
        os.chdir("../..")

        with open(output.dummy_output, 'w') as f:
            f.write("Analysis complete.\n")

rule get_torsionnet_500_input:
    output:
        "torsionnet_500/input/smiles.csv",
        "torsionnet_500/input/TNet500_minimal_dataset.json"
    shell:
        """
        mkdir -p torsionnet_500/input
        cd torsionnet_500/input
        curl https://zenodo.org/records/11385284/files/TNet500_minimal.zip?download=1 -o TNet500_minimal.zip
        unzip TNet500_minimal.zip
        rm TNet500_minimal.zip
        rm -r __MACOSX
        python ../scripts/create_dataset.py
        python ../scripts/extract_smiles.py
        cd ../..
        """

rule run_fits:
    input:
        config_file="configs/{config}.yaml",
        smiles_file="{benchmark_dir}/input/smiles.csv"
    output:
        force_field="{benchmark_dir}/output/{config}/combined_forcefield.offxml"
    run:
        run_bespokefit_all_smiles(input.config_file,
                                  input.smiles_file,
                                  wildcards.benchmark_dir,
                                  wildcards.config,
                                  from_precomputed=False)

# rule analyse_fits:
#     input:
#         force_field="{benchmark_dir}/output/{config}/combined_forcefield.offxml",
#         input_data="{benchmark_dir}/input/input.json"
#     output:
#         dummy_output="{benchmark_dir}/analysis/{config}_dummy_output.txt"
#     run:
#         from yammbs.scripts.run_torsion_comparisons import main
#         from pathlib import Path
#         analysis_dir = Path(f"{wildcards.benchmark_dir}/analysis")
#         analysis_dir.mkdir(parents=True, exist_ok=True)
#         os.chdir(analysis_dir)

#         extra_force_fields = [
#             f"../output/{wildcards.config}/combined_forcefield.offxml"
#         ]

#         cmd = [
#             "yammbs_analyse_torsions",
#             "--base-force-fields", "openff_unconstrained-2.3.0-rc2.offxml",
#             "--base-force-fields", "openff_no_water_unconstrained-3.0.0-alpha0.offxml",
#             "--base-force-fields", "../../input_forcefields/espaloma.offxml",
#             "--qcarchive-torsion-data", f"../input/{os.path.basename(input.input_data)}",
#         ]

#         for ff in extra_force_fields:
#             cmd.extend(["--extra-force-fields", ff])

#         subprocess.run(cmd, check=True)
#         os.chdir("../..")

#         with open(output.dummy_output, 'w') as f:
#             f.write("Analysis complete.\n")

rule analyse_torsionnet_500:
    input:
        # config_file="configs/{config}.yaml",
        force_field="torsionnet_500/output/{config}/combined_forcefield.offxml",
        input_data="torsionnet_500/input/TNet500_minimal_dataset.json"
    output:
        dummy_output="torsionnet_500/analysis/{config}_dummy_output.txt"
    shell:
        """
        mkdir -p torsionnet_500/analysis
        cd torsionnet_500/analysis
        yammbs_analyse_torsions --base-force-fields openff_unconstrained-2.3.0-rc2.offxml \
        --extra-force-fields ../output/espaloma03/combined_forcefield.offxml \
        --extra-force-fields ../output/egret1_opt/combined_forcefield.offxml \
        --extra-force-fields ../output/{wildcards.config}/combined_forcefield.offxml \
        --qcarchive-torsion-data ../input/TNet500_minimal_dataset.json &&
        python ../scripts/get_summary.py {wildcards.config} &&
        touch {output.dummy_output}
        cd ../..
        """
        # """
        # mkdir -p torsionnet_500/analysis
        # cd torsionnet_500/analysis
        # yammbs_analyse_torsions --base-force-fields openff-2.2.1 \
        # --base-force-fields openff_unconstrained-2.3.0-rc2.offxml \
        # --base-force-fields openff_no_water_unconstrained-3.0.0-alpha0.offxml \
        # --extra-force-fields ../output/espaloma03/combined_forcefield.offxml \
        # --extra-force-fields ../output/{wildcards.config}/combined_forcefield.offxml \
        # --qcarchive-torsion-data ../input/TNet500_minimal_dataset.json &&
        # touch {output.dummy_output}
        # cd ../..
        # """
        # --extra-force-fields ../output/egret1_reg_metd/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_reg_metd/combined_forcefield.offxml \
        # yammbs_analyse_torsions --base-force-fields openff-2.2.1 \
        # --extra-force-fields ../output/espaloma03_sage_nb/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_opt/combined_forcefield.offxml \
        # --extra-force-fields ../output/espaloma03/combined_forcefield.offxml \
        # --extra-force-fields ../output/aimnet2/combined_forcefield.offxml \
        # --extra-force-fields ../output/aimnet2_metad/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_metad/combined_forcefield.offxml \

rule analyse_jacs_conformers_frags_torsions:
    input:
        # config_file="configs/{config}.yaml",
        force_field="jacs_set_conformers_frags_torsions/output/{config}/combined_forcefield.offxml",
        input_data="jacs_set_conformers_frags_torsions/input/input.json"
    output:
        dummy_output="jacs_set_conformers_frags_torsions/analysis/{config}_dummy_output.txt"
    shell:
        """
        mkdir -p jacs_set_conformers_frags_torsions/analysis
        cd jacs_set_conformers_frags_torsions/analysis
        yammbs_analyse_torsions --base-force-fields openff_unconstrained-2.3.0-rc2.offxml \
        --extra-force-fields ../../input_forcefields/espaloma.offxml \
        --extra-force-fields ../../input_forcefields/sage-default-bespoke.offxml \
        --extra-force-fields ../output/opt-aceff2-2it/combined_forcefield.offxml \
        --extra-force-fields ../output/opt-aceff2-2it-more-metad-500k/combined_forcefield.offxml \
        --extra-force-fields ../output/{wildcards.config}/combined_forcefield.offxml \
        --qcarchive-torsion-data ../input/input.json &&
        python ../scripts/get_summary.py {wildcards.config} &&
        touch {output.dummy_output}
        cd ../..
        """
        # --extra-force-fields ../output/opt-aceff2-2it/combined_forcefield.offxml \
        # --extra-force-fields ../output/md_plus_tor_min_longer_dual_ens_all_ml_energy_no_restr/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_opt_reg/combined_forcefield.offxml \
        # yammbs_analyse_torsions --base-force-fields openff_unconstrained-2.3.0-rc2.offxml \
        # --extra-force-fields ../../input_forcefields/espaloma.offxml \
        # --extra-force-fields ../output/egret1_opt_reg_ml_min_shorter/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_opt_reg/combined_forcefield.offxml \
        # --extra-force-fields ../output/egret1_opt_reg_ml_min_shorter/combined_forcefield.offxml \
        # python ../scripts/get_summary.py {wildcards.config} &&
        # --extra-force-fields ../../input_forcefields/egret1.offxml \
        # --extra-force-fields ../output/egret1_opt_reg/combined_forcefield.offxml \

rule get_jacs_conformers_input:
    output:
        "jacs_set_conformers/input/smiles.csv"
    shell:
        """
        cd jacs_set_conformers/input
        python ../scripts/extract_smiles.py
        cd ../..
        """

rule analyse_jacs_conformers:
    input:
        force_field="jacs_set_conformers/output/{config}/combined_forcefield.offxml",
        input_data="jacs_set_conformers/input/smiles.csv"
    output:
        dummy_output="jacs_set_conformers/analysis/{config}_dummy_output.txt"
    shell:
        """
        mkdir -p jacs_set_conformers/analysis
        cd jacs_set_conformers
        python scripts/analyse.py {config} ../{input.force_field}
        touch {output.dummy_output}
        cd ..
        """
